apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-configmap
  namespace: springpg
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://spring-postgres-service.springpg:5432/university
  SPRING_DATASOURCE_USERNAME: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: springpg
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  namespace: springpg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: radulovskia/app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spring-configmap
            - secretRef:
                name: spring-secret
